# Generated by Django 2.0.5 on 2018-06-30 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(whitelist='bluevine.com')])),
                ('username', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('TL', 'Team Leader'), ('PM', 'Product Manager')], max_length=2)),
            ],
        ),
    ]
