# Generated by Django 2.0.5 on 2018-06-30 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='group',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(whitelist=['bluevine'])]),
        ),
    ]
